export const auth = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT: "LOGOUT",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  TOKEN_REQUEST: "TOKEN_REQUEST",
  TOKEN_SUCCESS: "TOKEN_SUCCESS",
  TOKEN_FAILURE: "TOKEN_FAILURE",
};

export const contactTypes = {
  //CONTACT_
  POST_REQUEST: "POST_CONTACT_REQUEST",
  POST_SUCCESS: "POST_CONTACT_SUCCESS",
  POST_FAILURE: "POST_CONTACT_FAILURE",

  GET_REQUEST: "GET_CONTACTS_REQUEST",
  GET_SUCCESS: "GET_CONTACTS_SUCCESS",
  GET_FAILURE: "GET_CONTACTS_FAILURE",

  DELETE_REQUEST: "DELETE_CONTACT_REQUEST",
  DELETE_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_FAILURE: "DELETE_CONTACT_FAILURE",

  UPDATE_REQUEST: "UPDATE_CONTACT_REQUEST",
  UPDATE_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  UPDATE_FAILURE: "UPDATE_CONTACT_FAILURE",

  CLEAR_REQUEST: "CLEAR_CONTACT_REQUEST",
  CLEAR_SUCCESS: "CLEAR_CONTACT_SUCCESS",
  CLEAR_FAILURE: "CLEAR_CONTACT_FAILURE",
};

export const bookTypes = {
  //BOOK_
  POST_REQUEST: "POST_BOOK_REQUEST",
  POST_SUCCESS: "POST_BOOK_SUCCESS",
  POST_FAILURE: "POST_BOOK_FAILURE",

  GET_REQUEST: "GET_BOOK_REQUEST",
  GET_SUCCESS: "GET_BOOK_SUCCESS",
  GET_FAILURE: "GET_BOOK_FAILURE",

  GET_ONE_REQUEST: "GET_ONEBOOK_REQUEST",
  GET_ONE_SUCCESS: "GET_ONEBOOK_SUCCESS",
  GET_ONE_FAILURE: "GET_ONEBOOK_FAILURE",

  DELETE_REQUEST: "DELETE_BOOK_REQUEST",
  DELETE_SUCCESS: "DELETE_BOOK_SUCCESS",
  DELETE_FAILURE: "DELETE_BOOK_FAILURE",

  UPDATE_REQUEST: "UPDATE_BOOK_REQUEST",
  UPDATE_SUCCESS: "UPDATE_BOOK_SUCCESS",
  UPDATE_FAILURE: "UPDATE_BOOK_FAILURE",

  MAKE_FAVOURITE_REQUEST: "MAKE_FAVOURITE_REQUEST",
  MAKE_FAVOURITE_SUCCESS: "MAKE_FAVOURITE_SUCCESS",
  MAKE_FAVOURITE_FAILURE: "MAKE_FAVOURITE_FAILURE",
};

export const errorTypes = {
  CLEAR_ERRORS: "CLEAR_ERRORS",
};
